server:
  port: 8081

spring:
  datasource:
      name: MySQL Connection
      url: jdbc:mysql://localhost:3306/monamour
      username: root
      password: rajan123
      driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  show-sql: true
  ddl-auto: update

app:
  jwtSecret: ThisIsASecretKeyWithAtLeast32CharactersKeyWithAtLeast32CharactersKeyWithAtLeast32Characters
  jwtExpirationMs: 3000000